### PR TITLE
Fix comparisons for mixed-signedness integral reps

### LINKED ISSUE #428: Comparisons with mixed-rep quantity types can suppress warnings inappropriately
See <https://godbolt.org/z/MfjEj19Yn>.  Basically, mixed-sign comparisons can produce incorrect results (e.g., `-1 > 1u` is generally `true`).  The problem for Au is that when we compare two `Quantity` types with a different unit **or** rep, we explicitly cast them to their common unit-and-rep, and then perform the comparison for the same types.

What we really should be doing is converting them to their common _units_, and then doing the comparison with respect to the raw numbers.  Implementing this will be tricky and subtle, because we have to consider things like:

- Hidden friends (which are important for supporting shapeshifter types like `Zero`, in a low-effort and symmetric way), which means there will generally be _two_ matching implementations for every mixed-rep comparison.
- Negative units, which means we need to pass the operands in the reversed order.

We'll need to think and explore to figure out the best way to solve this.

The above is all about getting the Au code to produce compiler warnings/errors in the same situations that the raw numeric code does.  But we'll want to go further: we'll also want a solution for _actually performing the comparison correctly_: something equivalent to `std::cmp_less` and friends (from C++20).

### PR DESCRIPTION
**Pull request by chiphogg**
We upgrade our operator replacements (`Less`, `Equal`, etc.) to detect
the situation where both reps have integral type, and delegate to the
more robust comparators that handle that case directly.

Fixes #428.

### CODE REVIEW

File: release/common_test_cases.hh [hunk 1]
```diff
@@ -50,5 +50,7 @@ TEST(CommonSingleFile, IncludesMathFunctions) {
     EXPECT_DOUBLE_EQ(sin(radians(get_value<double>(PI / mag<2>()))), 1.0);
 }
 
+TEST(CommonSingleFile, MixedSignQuantityComparisonWorks) { EXPECT_LT(meters(-1), meters(1u)); }
```
Comment (hoffbrinkle) [inline release/common_test_cases.hh:53]: Huh, I totally missed this file when doing the Matcher conversions, didn't realize there was code outside of `au/`.

**Review by hoffbrinkle — APPROVED** [review]

File: release/common_test_cases.hh (hunk 1 above)
Comment (chiphogg) [reply release/common_test_cases.hh:53]: Oops... I thought I had a good `EXPECT_THAT` habit going now.  Oh well, we can convert the whole file at once anyway.
